HIGH = {
    1: [
        "money deducted",
        "payment fraud",
        "scholarship blocked",
        "fee payment failed",
        "wrong amount deducted",
        "double payment",
        "unauthorized payment",
        "fee deadline today",
        "account locked",
        "financial fraud",
        "scholarship payment missing",
        "exam fee blocked",
        "fee payment blocked",
        "refund fraud",
        "payment error"
    ],

    2: [
        "admission blocked",
        "enrollment blocked",
        "admission cancelled",
        "admission deadline today",
        "seat cancelled",
        "application rejected",
        "admission payment failed",
        "document verification blocked",
        "enrollment deadline",
        "registration blocked",
        "admission portal down",
        "application deadline today",
        "admission fee failed",
        "seat allocation error",
        "admission status missing"
    ],

    # 3 = EXAM CELL
    3: [
        "exam registration blocked",
        "hall ticket unavailable",
        "exam form blocked",
        "exam registration deadline",
        "exam form deadline",
        "hall ticket missing",
        "exam registration failed",
        "exam portal down",
        "exam form rejected",
        "exam payment failed",
        "exam enrollment blocked",
        "exam registration error",
        "hall ticket blocked",
        "exam eligibility error",
        "exam form submission failed"
    ],

    4: [
        "fire in library",
        "unsafe library",
        "library fire",
        "electrical fire library",
        "smoke in library",
        "electrical shock library",
        "exposed wiring library",
        "building collapse library",
        "emergency exit blocked",
        "library ceiling collapse",
        "library gas leak",
        "dangerous wiring",
        "structural damage library",
        "serious injury library",
        "library emergency"
    ],

    5: [
        "hostel fire",
        "gas leak",
        "electrical shock",
        "hostel electrical fire",
        "hostel building collapse",
        "exposed wiring hostel",
        "major water flooding",
        "unsafe hostel building",
        "hostel emergency",
        "room fire",
        "gas cylinder leak hostel",
        "serious injury hostel",
        "smoke in hostel",
        "dangerous electrical fault",
        "hostel ceiling collapse"
    ],

    6: [
        "sewage overflow",
        "major flooding",
        "contaminated water",
        "sewage leak",
        "sewage entering room",
        "sewage entering building",
        "major water leak",
        "flooded building",
        "flooded classroom",
        "flooded hostel",
        "toxic water",
        "unsafe drinking water",
        "broken sewage pipe",
        "major drainage failure",
        "water contamination"
    ],

    # 7 = CANTEEN
    7: [
        "food poisoning",
        "contaminated food",
        "gas leak",
        "food contamination",
        "spoiled food",
        "rotten food",
        "unsafe food",
        "food poisoning symptoms",
        "gas cylinder leak",
        "kitchen fire",
        "canteen fire",
        "toxic food",
        "food allergy emergency",
        "burn injury",
        "serious food illness"
    ],

    8: [
        "fire",
        "electrical shock",
        "exposed wiring",
        "building collapse",
        "structural collapse",
        "electrical fire",
        "major flooding",
        "unsafe building",
        "ceiling collapse",
        "dangerous wiring",
        "broken electrical panel",
        "gas leak building",
        "major structural damage",
        "building emergency",
        "serious infrastructure damage"
    ],

    9: [
        "server down",
        "data loss",
        "security breach",
        "system crash",
        "database failure",
        "hacked account",
        "cyber attack",
        "ransomware attack",
        "data breach",
        "server failure",
        "network completely down",
        "system unavailable",
        "critical software failure",
        "unauthorized access",
        "college portal down"
    ],

    10: [
        "fire",
        "accident",
        "injury",
        "serious accident",
        "medical emergency",
        "life threatening",
        "building emergency",
        "major safety issue",
        "dangerous situation",
        "serious safety problem",
        "emergency situation",
        "major accident",
        "critical issue",
        "immediate danger",
        "safety emergency"
    ]
}


MEDIUM = {
    1: [
        "fee issue",
        "refund",
        "payment issue",
        "account issue",
        "fee correction",
        "wrong fee amount",
        "fee receipt issue",
        "payment pending",
        "fee status not updated",
        "transaction pending",
        "scholarship issue",
        "scholarship status",
        "account balance issue",
        "fee details",
        "payment confirmation",
        "invoice issue",
        "billing issue",
        "fee adjustment",
        "payment confirmation missing",
        "financial information"
    ],

    2: [
        "document issue",
        "application issue",
        "admission query",
        "document verification",
        "application status",
        "admission status",
        "course selection issue",
        "application correction",
        "document upload issue",
        "application update",
        "admission information",
        "enrollment information",
        "course information",
        "seat information",
        "application details",
        "admission documents",
        "registration issue",
        "student registration",
        "application form issue",
        "admission process"
    ],

    # 3 = EXAM CELL
    3: [
        "exam issue",
        "registration issue",
        "exam form",
        "exam timetable issue",
        "exam schedule",
        "exam information",
        "exam subject issue",
        "exam centre issue",
        "exam seat issue",
        "internal marks issue",
        "exam marks issue",
        "result issue",
        "result correction",
        "exam attendance issue",
        "exam eligibility",
        "exam application",
        "exam instructions",
        "exam notification",
        "exam details",
        "examination query"
    ],

    4: [
        "book issue",
        "library service",
        "book availability",
        "book reservation",
        "book return issue",
        "library computer issue",
        "catalogue issue",
        "library timing",
        "library access issue",
        "membership issue",
        "library account issue",
        "book renewal",
        "book search issue",
        "study area issue",
        "library cleanliness",
        "library maintenance",
        "library system issue",
        "library printer issue",
        "library internet issue",
        "library resource issue"
    ],

    5: [
        "room issue",
        "water issue",
        "hostel maintenance",
        "room maintenance",
        "bathroom issue",
        "washroom issue",
        "hostel cleanliness",
        "room cleanliness",
        "water supply issue",
        "electricity issue",
        "room light issue",
        "room fan issue",
        "hostel furniture issue",
        "bed issue",
        "hostel internet issue",
        "hostel security issue",
        "room lock issue",
        "hostel common area",
        "hostel maintenance request",
        "hostel facility issue"
    ],

    6: [
        "water leakage",
        "cleaning issue",
        "drainage issue",
        "blocked drain",
        "leaking tap",
        "broken pipe",
        "water supply issue",
        "washroom cleaning",
        "dirty washroom",
        "dirty floor",
        "drain blockage",
        "plumbing repair",
        "toilet issue",
        "bathroom maintenance",
        "cleaning required",
        "garbage collection",
        "waste disposal",
        "drainage maintenance",
        "water tap issue",
        "sanitation issue"
    ],

    # 7 = CANTEEN
    7: [
        "food quality",
        "cleanliness",
        "food complaint",
        "food taste",
        "stale food",
        "cold food",
        "undercooked food",
        "overcooked food",
        "food hygiene",
        "kitchen cleanliness",
        "canteen cleanliness",
        "dirty plates",
        "dirty tables",
        "food availability",
        "food portion",
        "meal quality",
        "canteen service",
        "food serving issue",
        "canteen maintenance",
        "drinking water issue"
    ],

    8: [
        "fan not working",
        "light not working",
        "classroom issue",
        "classroom maintenance",
        "broken chair",
        "broken desk",
        "projector issue",
        "smart board issue",
        "classroom cleanliness",
        "air conditioning issue",
        "lift issue",
        "door repair",
        "window repair",
        "corridor maintenance",
        "laboratory maintenance",
        "building maintenance",
        "classroom equipment",
        "electricity issue",
        "infrastructure repair",
        "campus maintenance"
    ],

    9: [
        "login issue",
        "network issue",
        "internet issue",
        "password issue",
        "account login",
        "WiFi issue",
        "slow internet",
        "website issue",
        "portal issue",
        "email issue",
        "software issue",
        "application error",
        "computer issue",
        "printer issue",
        "system login",
        "account access",
        "network connection",
        "internet connection",
        "software error",
        "technical support"
    ],

    10: [
        "general issue",
        "service issue",
        "facility issue",
        "student issue",
        "campus issue",
        "college service",
        "general complaint",
        "facility maintenance",
        "student service",
        "campus service",
        "general information",
        "service request",
        "college facility",
        "common area issue",
        "campus cleanliness",
        "student facility",
        "general maintenance",
        "college information",
        "administrative issue",
        "other complaint"
    ]
}


LOW = {
    1: [
        "receipt",
        "information",
        "fee information",
        "fee receipt",
        "payment information",
        "account information",
        "fee structure",
        "payment details",
        "scholarship information",
        "fee enquiry",
        "account details",
        "payment query",
        "financial query",
        "invoice information",
        "general fee query"
    ],

    2: [
        "information",
        "query",
        "admission information",
        "course query",
        "course information",
        "application information",
        "document information",
        "admission enquiry",
        "course enquiry",
        "registration information",
        "application enquiry",
        "college admission query",
        "eligibility information",
        "general admission query",
        "admission details"
    ],

    # 3 = EXAM CELL
    3: [
        "timetable",
        "information",
        "exam timetable",
        "exam information",
        "exam schedule",
        "exam notice",
        "exam rules",
        "exam guidelines",
        "exam instructions",
        "exam dates",
        "exam timing",
        "subject information",
        "exam enquiry",
        "result information",
        "examination details"
    ],

    4: [
        "reading room",
        "seating",
        "reading room information",
        "library timing",
        "book information",
        "book enquiry",
        "library enquiry",
        "library rules",
        "library membership",
        "reading area",
        "study space",
        "book list",
        "library catalogue",
        "library information",
        "library timings"
    ],

    5: [
        "furniture",
        "paint",
        "room furniture",
        "hostel information",
        "hostel timing",
        "room information",
        "hostel rules",
        "hostel enquiry",
        "room enquiry",
        "bed information",
        "hostel facilities",
        "hostel common area",
        "hostel notice",
        "hostel guidelines",
        "hostel details"
    ],

    6: [
        "dust",
        "minor leakage",
        "cleaning request",
        "dustbin",
        "waste collection",
        "minor cleaning",
        "cleaning information",
        "washroom information",
        "toilet cleaning",
        "bathroom cleaning",
        "cleaning schedule",
        "sanitation information",
        "drain information",
        "water supply information",
        "plumbing enquiry"
    ],

    # 7 = CANTEEN
    7: [
        "menu",
        "seating",
        "menu information",
        "food menu",
        "canteen menu",
        "seating arrangement",
        "table availability",
        "meal information",
        "food options",
        "canteen information",
        "price information",
        "food price",
        "canteen timing",
        "meal timing",
        "canteen enquiry"
    ],

    8: [
        "paint",
        "chair",
        "desk",
        "classroom information",
        "building information",
        "campus information",
        "facility information",
        "room information",
        "classroom enquiry",
        "campus enquiry",
        "infrastructure information",
        "building enquiry",
        "facility enquiry",
        "maintenance information",
        "campus facility"
    ],

    9: [
        "software update",
        "password change",
        "software information",
        "IT information",
        "technical information",
        "computer information",
        "network information",
        "WiFi information",
        "internet information",
        "portal information",
        "login information",
        "account information",
        "email information",
        "software enquiry",
        "technical enquiry"
    ],

    10: [
        "suggestion",
        "feedback",
        "general suggestion",
        "general feedback",
        "facility suggestion",
        "service suggestion",
        "student feedback",
        "campus feedback",
        "college suggestion",
        "improvement suggestion",
        "general enquiry",
        "information request",
        "general information",
        "feedback request",
        "service feedback"
    ]
}